spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-gmail-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
